// Code generated by gonectl. DO NOT EDIT.

package mock

import (
	"github.com/gone-io/gone/v2"
	gomock "go.uber.org/mock/gomock"
)

func MockLoader(loader gone.Loader, ctrl *gomock.Controller) {
	_ = loader.Load(NewMockIDependent(ctrl))
	_ = loader.Load(NewMockIUserLogin(ctrl))
	_ = loader.Load(NewMockIUser(ctrl))
	_ = loader.Load(NewMockIUserToken(ctrl))
}
