// Code generated by goneCtr. DO NOT EDIT.
package goner_define

import "github.com/gone-io/gone/v2"

func init() {
	gone.Default.
		Load(&greeting{}).
		Load(&readmeResource{}).
		Load(&helloTool{})
}
