// Code generated by gonectl. DO NOT EDIT.
package main

import (
	"github.com/gone-io/gone/v2"
	"github.com/gone-io/goner/g"
	"github.com/gone-io/goner/gin"
	"github.com/gone-io/goner/gorm"
	"github.com/gone-io/goner/gorm/mysql"
	"github.com/gone-io/goner/tracer/gls"
	"github.com/gone-io/goner/viper"
	zap "github.com/gone-io/goner/zap"
)

// load installed gone module LoadFunc
var loaders = []gone.LoadFunc{
	gin.Load,
	gls.Load,
	gorm.Load,
	mysql.Load,
	viper.Load,
	zap.Load,
}

func GoneModuleLoad(loader gone.Loader) error {
	var ops []*g.LoadOp
	for _, f := range loaders {
		ops = append(ops, g.F(f))
	}
	return g.BuildOnceLoadFunc(ops...)(loader)
}
