// Code generated by gonectl. DO NOT EDIT.
package collect

import (
	"github.com/gone-io/gone/v2"
	"github.com/gone-io/goner/g"
	http1 "github.com/gone-io/goner/otel/log/http"
	"github.com/gone-io/goner/otel/tracer/http"
	"github.com/gone-io/goner/tracer/gid"
	"github.com/gone-io/goner/viper"
	zap "github.com/gone-io/goner/zap"
)

// load installed gone module LoadFunc
var loaders = []gone.LoadFunc{
	gid.Load,
	http.Load,
	http1.Load,
	viper.Load,
	zap.Load,
}

func GoneModuleLoad(loader gone.Loader) error {
	var ops []*g.LoadOp
	for _, f := range loaders {
		ops = append(ops, g.F(f))
	}
	return g.BuildOnceLoadFunc(ops...)(loader)
}
