// Code generated by gonectr. DO NOT EDIT.

package main

import (
	_ "template_module"
	_ "template_module/internal/controller"
	_ "template_module/internal/module"
	_ "template_module/internal/module/dependent"
	_ "template_module/internal/module/user"
	_ "template_module/internal/router"
)
