// Code generated by gonectr. DO NOT EDIT.

package main

import (
	_ "examples/gin_xorm_viper"
	_ "examples/gin_xorm_viper/internal/controller"
	_ "examples/gin_xorm_viper/internal/module"
	_ "examples/gin_xorm_viper/internal/module/dependent"
	_ "examples/gin_xorm_viper/internal/module/user"
	_ "examples/gin_xorm_viper/internal/router"
)
