// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nacos-group/nacos-sdk-go/v2/clients/config_client (interfaces: IConfigClient)
//
// Generated by this command:
//
//	mockgen -destination=nacos_mock.go -package=nacos github.com/nacos-group/nacos-sdk-go/v2/clients/config_client IConfigClient
//

// Package nacos is a generated GoMock package.
package nacos

import (
	reflect "reflect"

	model "github.com/nacos-group/nacos-sdk-go/v2/model"
	vo "github.com/nacos-group/nacos-sdk-go/v2/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIConfigClient is a mock of IConfigClient interface.
type MockIConfigClient struct {
	ctrl     *gomock.Controller
	recorder *MockIConfigClientMockRecorder
	isgomock struct{}
}

// MockIConfigClientMockRecorder is the mock recorder for MockIConfigClient.
type MockIConfigClientMockRecorder struct {
	mock *MockIConfigClient
}

// NewMockIConfigClient creates a new mock instance.
func NewMockIConfigClient(ctrl *gomock.Controller) *MockIConfigClient {
	mock := &MockIConfigClient{ctrl: ctrl}
	mock.recorder = &MockIConfigClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConfigClient) EXPECT() *MockIConfigClientMockRecorder {
	return m.recorder
}

// CancelListenConfig mocks base method.
func (m *MockIConfigClient) CancelListenConfig(params vo.ConfigParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelListenConfig", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelListenConfig indicates an expected call of CancelListenConfig.
func (mr *MockIConfigClientMockRecorder) CancelListenConfig(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelListenConfig", reflect.TypeOf((*MockIConfigClient)(nil).CancelListenConfig), params)
}

// CloseClient mocks base method.
func (m *MockIConfigClient) CloseClient() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseClient")
}

// CloseClient indicates an expected call of CloseClient.
func (mr *MockIConfigClientMockRecorder) CloseClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseClient", reflect.TypeOf((*MockIConfigClient)(nil).CloseClient))
}

// DeleteConfig mocks base method.
func (m *MockIConfigClient) DeleteConfig(param vo.ConfigParam) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfig", param)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteConfig indicates an expected call of DeleteConfig.
func (mr *MockIConfigClientMockRecorder) DeleteConfig(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfig", reflect.TypeOf((*MockIConfigClient)(nil).DeleteConfig), param)
}

// GetConfig mocks base method.
func (m *MockIConfigClient) GetConfig(param vo.ConfigParam) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", param)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockIConfigClientMockRecorder) GetConfig(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockIConfigClient)(nil).GetConfig), param)
}

// ListenConfig mocks base method.
func (m *MockIConfigClient) ListenConfig(params vo.ConfigParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenConfig", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenConfig indicates an expected call of ListenConfig.
func (mr *MockIConfigClientMockRecorder) ListenConfig(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenConfig", reflect.TypeOf((*MockIConfigClient)(nil).ListenConfig), params)
}

// PublishConfig mocks base method.
func (m *MockIConfigClient) PublishConfig(param vo.ConfigParam) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishConfig", param)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishConfig indicates an expected call of PublishConfig.
func (mr *MockIConfigClientMockRecorder) PublishConfig(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishConfig", reflect.TypeOf((*MockIConfigClient)(nil).PublishConfig), param)
}

// SearchConfig mocks base method.
func (m *MockIConfigClient) SearchConfig(param vo.SearchConfigParam) (*model.ConfigPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchConfig", param)
	ret0, _ := ret[0].(*model.ConfigPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchConfig indicates an expected call of SearchConfig.
func (mr *MockIConfigClientMockRecorder) SearchConfig(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchConfig", reflect.TypeOf((*MockIConfigClient)(nil).SearchConfig), param)
}
