// Code generated by gonectl. DO NOT EDIT.
package server
import (
	"github.com/gone-io/gone/v2"
	"github.com/gone-io/goner/g"
	grpc1 "github.com/gone-io/goner/grpc"
	"github.com/gone-io/goner/otel/tracer/grpc"
	"github.com/gone-io/goner/viper"
)

// load installed gone module LoadFunc
var loaders = []gone.LoadFunc{
	grpc.Load,
	grpc1.ServerLoad,
	viper.Load,
}

func GoneModuleLoad(loader gone.Loader) error {
	var ops []*g.LoadOp
	for _, f := range loaders {
		ops = append(ops, g.F(f))
	}
	return g.BuildOnceLoadFunc(ops...)(loader)
}
