// Code generated by gonectr. DO NOT EDIT.
package simple
import(
	"github.com/gone-io/gone/v2"
	"github.com/gone-io/goner/g"
	"github.com/gone-io/goner/viper"
)

// load installed gone module LoadFunc
var loaders = []gone.LoadFunc{
	viper.Load,
}

func GoneModuleLoad(loader gone.Loader) error {
	var ops []*g.LoadOp
	for _, f := range loaders {
		ops = append(ops, g.F(f))
	}
	return g.BuildOnceLoadFunc(ops...)(loader)
}
